[package]
name = "micro-autoenc"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "micro-autoenc"
path = "src/main.rs"
required-features = ["train"]

[dependencies]
anyhow = { version = "1", optional = true }
burn = {
  version = "=0.22.0-pre.4",
  default-features = false,
  features = ["flex"],
}
clap = { version = "4.6.7", features = ["derive", "wrap_help"], optional = true }
hound = { version = "3.5", optional = true }
polars = {
  version = "0.55",
  default-features = false,
  features = [
    "dtype-struct",
    "parquet",
  ],
  optional = true,
}
rand = { version = "0.10", optional = true }
serde_json = { version = "1.0.151", optional = true }

[dev-dependencies]
tempfile = "3"

[features]
default = ["cli", "train"]
cli = ["dep:clap", "dep:serde_json"]
train = [
  "burn/extension",
  "burn/metal",
  "burn/metrics",
  "burn/std",
  "burn/train",
  "burn/tui",
  "dep:anyhow",
  "dep:clap",
  "dep:hound",
  "dep:polars",
  "dep:rand",
]

[lints]
workspace = true
